"""

-- Generated by Software Ideas Modeler (Trial Version)
"""
class Point:
    def __init__(self):		
        """
        
        -- Generated by Software Ideas Modeler (Trial Version)
        """
        self.__x =0
        """
        
        -- Generated by Software Ideas Modeler (Trial Version)
        """
        self.__y =0
        
    
    """
    
    -- Generated by Software Ideas Modeler (Trial Version)
    """
    def __str__ (self):		
        # implementation
        pass        

    """
    
    -- Generated by Software Ideas Modeler (Trial Version)
    """
    def set (self):		
        # implementation
        pass        

    
    
    
